version: "3.9"
services:
  frontend:
    image: react
    ports: 
      - "3000:3000"
  backend:
    image: flask
    ports:
      - "5000:5000"
    networks: 
      - thingnet
    env_file: 
      - .env
  db:
    image: mongo
    networks: 
      - thingnet
networks:
  thingnet:
